# Generated by Django 5.2.12 on 2026-03-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('{{ project_name }}_wtrx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customimage',
            name='credit',
            field=models.CharField(blank=True, help_text="Photographer or source attribution (e.g. 'Photo: Jane Smith').", max_length=255, verbose_name='credit'),
        ),
    ]
